In [2]:
!unzip /content/archive.zip

Archive:  /content/archive.zip
  inflating: tmdb_5000_credits.csv
  inflating: tmdb_5000_movies.csv

In [3]:
import pandas as pd

In [11]:
credits = pd.read_csv('/content/tmdb_5000_credits.csv')
movies = pd.read_csv('/content/tmdb_5000_movies.csv')

In [12]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [13]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [14]:
print("Movies Dataset:", movies.shape)
print("Credits Dataset:", credits.shape)

Movies Dataset: (4803, 20)
Credits Dataset: (4803, 4)

In [15]:
print("Movies Columns:")
print(movies.columns)

print("\nCredits Columns:")
print(credits.columns)

Movies Columns:
Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

Credits Columns:
Index(['movie_id', 'title', 'cast', 'crew'], dtype='object')

In [16]:
merged_df = pd.merge(
    movies,
    credits,
    left_on="id",
    right_on="movie_id",
    how="inner"
)

In [18]:
print("Merged Dataset Shape:", merged_df.shape)

merged_df.head(1)

Merged Dataset Shape: (4803, 24)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,spoken_languages,status,tagline,title_x,vote_average,vote_count,movie_id,title_y,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [19]:
merged_df.rename(columns={'title_x': 'title'}, inplace=True)

In [20]:
merged_df = merged_df[
    [
        'id',
        'title',
        'overview',
        'genres',
        'keywords',
        'cast',
        'crew',
        'vote_average',
        'vote_count',
        'popularity'
    ]
]

In [21]:
merged_df.head(1)

,id,title,overview,genres,keywords,cast,crew,vote_average,vote_count,popularity
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",7.2,11800,150.437577

In [22]:
import ast

In [23]:
def convert(text):
    items = ast.literal_eval(text)
    return [item['name'] for item in items]

In [24]:
merged_df['genres'] = merged_df['genres'].apply(convert)
merged_df['keywords'] = merged_df['keywords'].apply(convert)

In [25]:
def convert_cast(text):
    items = ast.literal_eval(text)
    return [item['name'] for item in items[:3]]

In [26]:
merged_df['cast'] = merged_df['cast'].apply(convert_cast)

In [27]:
def fetch_director(text):
    items = ast.literal_eval(text)

    directors = []

    for item in items:
        if item['job'] == 'Director':
            directors.append(item['name'])

    return directors

In [28]:
merged_df['crew'] = merged_df['crew'].apply(fetch_director)

In [29]:
merged_df.head(1)

,id,title,overview,genres,keywords,cast,crew,vote_average,vote_count,popularity
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],7.2,11800,150.437577

In [36]:
merged_df.dtypes

id                int64
title            object
overview         object
genres           object
keywords         object
cast             object
crew             object
vote_average    float64
vote_count        int64
popularity      float64
dtype: object

In [30]:
merged_df.isnull().sum()

id              0
title           0
overview        3
genres          0
keywords        0
cast            0
crew            0
vote_average    0
vote_count      0
popularity      0
dtype: int64

In [31]:
merged_df.dropna(inplace=True)

In [37]:
print(type(merged_df.loc[0, 'genres']))
print(type(merged_df.loc[0, 'keywords']))
print(type(merged_df.loc[0, 'cast']))
print(type(merged_df.loc[0, 'crew']))

<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>

In [38]:
merged_df['id'].duplicated().sum()

np.int64(0)

In [39]:
merged_df['title'].duplicated().sum()

np.int64(3)

In [40]:
merged_df['id'].duplicated().sum()

np.int64(0)

In [42]:
list_cols = ['genres', 'keywords', 'cast', 'crew']

for col in list_cols:
    merged_df[col] = merged_df[col].apply(tuple)

merged_df.drop_duplicates(inplace=True)

In [43]:
merged_df['overview'] = merged_df['overview'].apply(lambda x: x.split())

In [44]:
def collapse(lst):
    return [i.replace(" ", "") for i in lst]

In [45]:
merged_df['genres'] = merged_df['genres'].apply(collapse)
merged_df['keywords'] = merged_df['keywords'].apply(collapse)
merged_df['cast'] = merged_df['cast'].apply(collapse)
merged_df['crew'] = merged_df['crew'].apply(collapse)

In [46]:
merged_df['tags'] = (
    merged_df['overview'] +
    merged_df['genres'] +
    merged_df['keywords'] +
    merged_df['cast'] +
    merged_df['crew']
)

In [47]:
merged_df.head(1)

,id,title,overview,genres,keywords,cast,crew,vote_average,vote_count,popularity,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],7.2,11800,150.437577,"[In, the, 22nd, century,, a, paraplegic, Marin..."

In [48]:
merged_df[['title', 'tags']].head()

,title,tags
0,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [49]:
new_df = merged_df[['id', 'title', 'tags']]

In [50]:
new_df.head(1)

      id   title                                               tags
0  19995  Avatar  [In, the, 22nd, century,, a, paraplegic, Marin...

In [51]:
new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

/tmp/ipykernel_1447/1824047427.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

In [52]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [53]:
new_df['tags'] = new_df['tags'].apply(lambda x: x.lower())

/tmp/ipykernel_1447/1380776331.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: x.lower())

In [54]:
new_df['tags'][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron'

In [55]:
import nltk
from nltk.stem.porter import PorterStemmer

In [56]:
ps = PorterStemmer()

In [57]:
def stem(text):
    words = []

    for word in text.split():
        words.append(ps.stem(word))

    return " ".join(words)

In [58]:
new_df['tags'] = new_df['tags'].apply(stem)

/tmp/ipykernel_1447/3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [59]:
new_df['tags'].head()

0    in the 22nd century, a parapleg marin is dispa...
1    captain barbossa, long believ to be dead, ha c...
2    a cryptic messag from bond’ past send him on a...
3    follow the death of district attorney harvey d...
4    john carter is a war-weary, former militari ca...
Name: tags, dtype: object

In [60]:
from sklearn.feature_extraction.text import CountVectorizer

In [61]:
cv = CountVectorizer(
    max_features=5000,
    stop_words='english'
)

In [62]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [63]:
vectors.shape

(4800, 5000)

In [64]:
from sklearn.metrics.pairwise import cosine_similarity

In [65]:
similarity = cosine_similarity(vectors)

In [66]:
similarity.shape

(4800, 4800)

In [67]:
similarity[0]

array([1.        , 0.08346223, 0.0860309 , ..., 0.04499213, 0.        ,
       0.        ])

In [68]:
def recommend(movie):

    # Find the movie index
    movie_index = new_df[new_df['title'] == movie].index[0]

    # Similarity scores
    distances = similarity[movie_index]

    # Sort by similarity (highest first)
    movies_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x: x[1]
    )[1:6]  # Skip the first one (the movie itself)

    # Print recommendations
    for movie in movies_list:
        print(new_df.iloc[movie[0]].title)

In [69]:
recommend("Avatar")

Aliens vs Predator: Requiem
Aliens
Falcon Rising
Independence Day
Titan A.E.

In [70]:
def recommend(movie):

    movie_index = new_df[new_df['title'] == movie].index[0]

    distances = similarity[movie_index]

    movies_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x: x[1]
    )[1:6]

    recommended_movies = []

    for item in movies_list:
        recommended_movies.append({
            "id": new_df.iloc[item[0]].id,
            "title": new_df.iloc[item[0]].title
        })

    return recommended_movies

In [71]:
recommend("Avatar")

[{'id': np.int64(440), 'title': 'Aliens vs Predator: Requiem'},
 {'id': np.int64(679), 'title': 'Aliens'},
 {'id': np.int64(270938), 'title': 'Falcon Rising'},
 {'id': np.int64(602), 'title': 'Independence Day'},
 {'id': np.int64(7450), 'title': 'Titan A.E.'}]

In [72]:
import pickle

pickle.dump(new_df, open('movies.pkl', 'wb'))

In [73]:
pickle.dump(similarity, open('similarity.pkl', 'wb'))

In [74]:
from google.colab import files

files.download('movies.pkl')
files.download('similarity.pkl')